from App.modules.api.api import API

app = API(city="Chicago", country="United States of America", zip_code='test', days=2)
print(app.current_weather)
print(app.current_weather_description)
print(app.current_temperature_average)
print(app.current_temperature_min)
print(app.current_temperature_max)
print(app.current_wind_speed)
print(app.current_wind_direction)
print(app.current_cloud_cover)
print(app.current_precipitation)
print(app.current_humidity)
print(app.uv_index_today)
print()
print(app.weather)
print(app.weather_description)
print(app.temperature_average)
print(app.temperature_min)
print(app.temperature_max)
print(app.wind_speed)
print(app.wind_direction)
print(app.cloud_cover)
print(app.precipitation)
print(app.humidity)
print()
print(app.uv_index_today)
print(app.get_radar_image_path('radar', 'radar',  'precipitation_cls', 8))
print(app.get_base_image_path(8))
